name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v1
        with:
          args: "check ."

      - name: Prepare environment
        run: cp .env.example .env

      - name: Build Docker Image
        run: docker compose build

      - name: Start and Verify Container
        run: |
          docker compose up -d

          sleep 5

          if [ $(docker inspect -f '{{.State.Running}}' int20h_ai_test_task) = "true" ]; then
            echo "The container has successfully started and is running in the background!"
          else
            echo "Error: Container crashed!"
            docker compose logs
            exit 1
          fi